# Generated by Django 6.0 on 2026-01-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=150, unique=True)),
                ('sr_no', models.PositiveIntegerField(unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('dorm', 'Dormitory')], max_length=20)),
                ('ac_non_ac', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=20)),
                ('room_rent', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTERAPP.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('address_doc', models.FileField(blank=True, null=True, upload_to='tenant_docs/address/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='tenant_docs/id_proof/')),
                ('join_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pending_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTERAPP.room')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_month', models.DateField()),
                ('previous_reading', models.PositiveIntegerField()),
                ('current_reading', models.PositiveIntegerField()),
                ('unit_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='MASTERAPP.tenant')),
            ],
        ),
    ]
