# Generated by Django 6.0 on 2026-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTERAPP', '0003_alter_facility_facility_name_alter_facility_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
