# Generated by Django 6.0 on 2026-01-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTERAPP', '0006_tenant_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_set', to='MASTERAPP.room'),
        ),
    ]
