# Generated by Django 6.0 on 2026-01-21 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTERAPP', '0009_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_rent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Partially_Occupied', 'Partially Occupied'), ('Reserved', 'Reserved'), ('Maintenance', 'Maintenance'), ('Blocked', 'Blocked')], default='Available', max_length=20),
        ),
    ]
