# Generated by Django 6.0 on 2026-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTERAPP', '0010_alter_room_room_rent_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ac_non_ac',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=20),
        ),
    ]
