# Generated by Django 6.0 on 2026-01-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTERAPP', '0004_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Dormitory', 'Dormitory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='MASTERAPP.room'),
        ),
    ]
