# Generated by Django 6.0 on 2026-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTERAPP', '0008_alter_tenant_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
